### ISSUE TITLE
[REPOSITORY] New Repository Strimzi Topic Integration connector

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#691]
### Name

egeria-connector-integration-topic-strimzi

### Owner

davidradl

### Deliverable

Provides an integration connector to bring in Kafka Topics by monitoring Strimzi custom resource definitions 

### Build, test and CI-CD process

answering the questions in order
Same as for the crux 
Gradle
Java
I suspect there already is one
Same as for Egeria core
Nothing out of the ordinary
Not needed

### Dependencies

The is the gradle.build file we have used for testing
`/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Contributors to the ODPi Egeria project.
 */

repositories {
        mavenCentral()
}
group = 'org.odpi.egeria'
version = 1
configurations {
    extralibs
}
apply plugin: 'java-library'
ext {
    egeriaversion = '3.2'
    logbackVersion = '1.2.6'
    jacksonVersion = '2.13.0'
    junitjupiterVersion = '5.8.1'
}
dependencies {
        implementation "org.slf4j:slf4j-api:${logbackVersion}"
        implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
        implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
        implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
        implementation "org.junit.jupiter:junit-jupiter:${junitjupiterVersion}"
        implementation "org.odpi.egeria:open-connector-framework:${egeriaversion}"
        implementation "org.odpi.egeria:audit-log-framework:${egeriaversion}"
        implementation "org.odpi.egeria:repository-services:${egeriaversion}"
        implementation "org.odpi.egeria:repository-services-apis:${egeriaversion}"
        implementation "org.odpi.egeria:topic-integrator-api:${egeriaversion}"
        implementation "org.odpi.egeria:kafka-open-metadata-topic-connector:${egeriaversion}"
        extralibs 'org.apache.httpcomponents:httpclient:4.5.13'
        configurations.compile.extendsFrom(configurations.extralibs)
}

test {
    useJUnitPlatform()
    dependencies {
        testCompile("org.junit.jupiter:junit-jupiter-api:5.7.0")
        testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.7.0"
        testImplementation "org.junit.jupiter:junit-jupiter-params:5.7.0"
        testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0")
    }
    testLogging {
        events "passed", "skipped", "failed"
    }
    reports {
        html.enabled = true
    }
    filter {
        includeTestsMatching "*Test"
    }
}

// Maven Central (technically sonatype oss) requires we distribute source and javadoc
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
// More Java language settings
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    sourceCompatibility = "11"
    targetCompatibility = "11"
    options.incremental = true
    options.fork = true
    options.failOnError = true
    options.compilerArgs << '-Xlint:unchecked' << '-Xlint:deprecation'
}

jar {
    from {
        configurations.extralibs.filter{it.exists()}
        .collect{it.isDirectory() ? it : zipTree(it)}
    }
}`

### Justification

There is no obvious repo to put this in

### Assumptions

Yes all true. 

### Additional Information

https://github.com/odpi/egeria/issues/6021

### Work Plan

Before creating the repo
- [x] review overall request & get clarifications
- [x] get approval on developer/TSC call from maintainers

Creating the repo
- [x] Create the repo under the odpi organization (default gitignore, license, readme)
- [x] Setup branch protection rules
- [x] Set pull request options (allow merge, squash, rebase, suggest updating, allow automerge, do not delete head)
- [x] Update security settings in repo (policy, advisories, alerts)
- [x] set up permissions

First steps
- [x] Initial code-drop (author)

Getting CI/CD started & refining settings
- [x] Add initial build script for PR (including gradle wrapper if required)
- [x] Add initial build script for merge

Further Refinement
- [x] Add link in egeria docs to new repo describing purpose etc       
- [x] Add required credentials for publishing to container repos, maven central etc
- [x] Add artifact signing if needed
- [x] Add dependabot config        
- [x] Add CodeQL 
- [x] Add to LFXSecurity
- [ ] Add to LFAnalytics
- [x] Add check for stale defects
- [x] Add standard issue tags

Release
- [x] Add release pipeline

**Comment by planetf1** [comment]
@juergenhemelt Can you handle this? This is just some missing docs -- documenting the connector in the connector catalog & documenting the release process.
