### ISSUE TITLE
[REPOSITORY] New Repository for Egeria lineage sample

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#692]
### Name

egeria-connector-integration-lineage-event-driven-sample

### Owner

davidradl

### Deliverable

Useful to bring in lineage to Egeria

### Build, test and CI-CD process

usual

### Dependencies

usual

### Justification

in line with the thinking behind a new repo for egeria-connector-repository-file-sample we would like one for this sample. The samples repo is coco based

### Assumptions

yes all true

### Work Plan

Before creating the repo
- [x] review overall request & get clarifications
- [x] get approval on developer/TSC call from maintainers

Creating the repo
- [x] Create the repo under the odpi organization (default gitignore, license, readme)
- [x] Setup branch protection rules
- [x] Set pull request options (allow merge, squash, rebase, suggest updating, allow automerge, do not delete head)
- [x] Update security settings in repo (policy, advisories, alerts)
- [x] set up permissions

First steps
- [ ] Initial code-drop (author)

Getting CI/CD started & refining settings
- [x] Add initial build script for PR (including gradle wrapper if required)
- [x] Add initial build script for merge

Further Refinement
- [ ] Add link in egeria docs to new repo describing purpose ( https://github.com/odpi/egeria-docs/blob/main/site/docs/education/tutorials/git-and-git-hub-tutorial/egeria-git-repositories.md ) 
- [ ] Add to connector catalog, if new repo is for connector ( https://github.com/odpi/egeria-docs/blob/main/site/docs/connectors/index.md )
- [ ] Add to release process docs ( https://github.com/odpi/egeria-docs/blob/main/site/docs/guides/contributor/release-process/index.md )
- [x] Add required credentials for publishing to container repos, maven central etc
- [x] Add artifact signing if needed
- [x] Add dependabot config        
- [x] Add CodeQL 
- [ ] Add to LFX ( https://projectadmin.lfx.linuxfoundation.org/project/a092M00001IV4JtQAL  ) for
  - [ ] LFXSecurity
  - [ ] LFAnalytics
- [x] Add check for stale defects
- [x] Add any required issue tags

Release
- [x] Add release pipeline

**Comment by planetf1** [comment]
@juergenhemelt Can you handle this? This is just some missing docs -- documenting the connector in the connector catalog & documenting the release process.
